-- 01_setup.sql
-- End-to-End Retail Sales Prediction ML Workflow Using Snowflake
-- Database: RETAIL_ML_DB
-- Schema: RETAIL_SCHEMA
-- Warehouse: RETAIL_ML_WH

CREATE OR REPLACE DATABASE RETAIL_ML_DB;
CREATE OR REPLACE SCHEMA RETAIL_ML_DB.RETAIL_SCHEMA;

CREATE OR REPLACE WAREHOUSE RETAIL_ML_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE RETAIL_ML_DB;
USE SCHEMA RETAIL_SCHEMA;
USE WAREHOUSE RETAIL_ML_WH;

-- The original ONLINE_RETAIL table was uploaded from the UCI Online Retail CSV
-- through Snowsight. Expected columns:
-- INVOICENO, STOCKCODE, DESCRIPTION, QUANTITY, INVOICEDATE,
-- UNITPRICE, CUSTOMERID, COUNTRY

-- Add transaction-level sales amount
CREATE OR REPLACE TABLE RETAIL_SALES AS
SELECT
    INVOICENO,
    STOCKCODE,
    DESCRIPTION,
    QUANTITY,
    INVOICEDATE,
    UNITPRICE,
    CUSTOMERID,
    COUNTRY,
    QUANTITY * UNITPRICE AS SALES_AMOUNT
FROM ONLINE_RETAIL;

-- Remove invalid quantities and prices
CREATE OR REPLACE TABLE RETAIL_SALES_CLEAN AS
SELECT *
FROM RETAIL_SALES
WHERE QUANTITY > 0
  AND UNITPRICE > 0;

-- Daily retail sales aggregation
CREATE OR REPLACE TABLE DAILY_RETAIL_SALES AS
SELECT
    TO_DATE(TO_TIMESTAMP(INVOICEDATE, 'DD-MM-YYYY HH24:MI')) AS SALES_DATE,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    COUNT(*) AS TRANSACTION_COUNT
FROM RETAIL_SALES_CLEAN
GROUP BY SALES_DATE
ORDER BY SALES_DATE;

-- Time-series features
CREATE OR REPLACE TABLE RETAIL_FORECAST_DATA AS
SELECT
    SALES_DATE,
    TOTAL_SALES,
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    EXTRACT(DAY FROM SALES_DATE) AS DAY,
    EXTRACT(DAYOFWEEK FROM SALES_DATE) AS DAY_OF_WEEK,
    LAG(TOTAL_SALES, 1) OVER (ORDER BY SALES_DATE) AS SALES_LAG_1,
    LAG(TOTAL_SALES, 7) OVER (ORDER BY SALES_DATE) AS SALES_LAG_7,
    LAG(TOTAL_SALES, 30) OVER (ORDER BY SALES_DATE) AS SALES_LAG_30,
    AVG(TOTAL_SALES) OVER (
        ORDER BY SALES_DATE
        ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING
    ) AS SALES_ROLLING_7
FROM DAILY_RETAIL_SALES;

-- Final ML dataset
CREATE OR REPLACE TABLE RETAIL_ML_FINAL AS
SELECT *
FROM RETAIL_FORECAST_DATA
WHERE SALES_LAG_1 IS NOT NULL
  AND SALES_LAG_7 IS NOT NULL
  AND SALES_LAG_30 IS NOT NULL
  AND SALES_ROLLING_7 IS NOT NULL;

-- Useful verification queries
SELECT COUNT(*) AS CLEAN_ROWS
FROM RETAIL_SALES_CLEAN;

SELECT MIN(SALES_DATE) AS START_DATE,
       MAX(SALES_DATE) AS END_DATE,
       COUNT(*) AS TOTAL_DAYS
FROM DAILY_RETAIL_SALES;

SELECT COUNT(*) AS ML_ROWS
FROM RETAIL_ML_FINAL;

SELECT *
FROM RETAIL_ML_FINAL
ORDER BY SALES_DATE
LIMIT 10;

-- Prediction table is created by the Python ML workflow:
-- RETAIL_SALES_PREDICTIONS
